version: '2'
services:
  rotor:
    image: turbinelabs/rotor
    volumes:
      - ./rotor-clusters.yml:/etc/rotor-clusters.yml
    environment:
      ROTOR_API_KEY: ${ROTOR_API_KEY}
      ROTOR_API_ZONE_NAME: ${ROTOR_API_ZONE_NAME}
      ROTOR_CMD: file
      ROTOR_FILE_FILENAME: /etc/rotor-clusters.yml
      ROTOR_FILE_FORMAT: yaml
    expose:
      - "50000"
    networks:
      envoymesh:
        aliases:
          - rotor
  front-envoy:
    image: turbinelabs/envoy-simple
    environment:
      ENVOY_NODE_CLUSTER: front-proxy
      ENVOY_NODE_ZONE: ${ROTOR_API_ZONE_NAME}
      ENVOY_XDS_HOST: rotor
    networks:
      - envoymesh
    expose:
      - "80"
      - "9999"
    ports:
      - "80:80"
      - "9999:9999"
  all-in-one-client:
    image: turbinelabs/all-in-one-client
    networks:
      envoymesh:
        ipv4_address: 10.0.0.10
    ports:
      - "8080"
  all-in-one-server-blue:
    image: turbinelabs/all-in-one-server
    environment:
      TBN_COLOR: 1B9AE4
      TBN_NAME: blue
    networks:
      envoymesh:
        ipv4_address: 10.0.0.11
    ports:
      - "8080"
  all-in-one-server-green:
    image: turbinelabs/all-in-one-server
    environment:
      TBN_COLOR: 1CAD0C
      TBN_NAME: green
    networks:
      envoymesh:
        ipv4_address: 10.0.0.12
    ports:
      - "8080"

networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.1/16
